### ISSUE TITLE
macOS "universal" wheel does not contain the Apple Silicon binary

### ISSUE THREAD

**Issue by pietrodn** [plasma-umass/slipcover#11]
When I try to install and run slipcover on a M1 Pro Mac, this is what I get:

```
$ python3 -m venv venv
$ venv/bin/pip install slipcover
Collecting slipcover
  Using cached slipcover-0.1.4-cp310-cp310-macosx_10_15_universal2.whl (22 kB)
Collecting tabulate
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Installing collected packages: tabulate, slipcover
Successfully installed slipcover-0.1.4 tabulate-0.8.9

$ venv/bin/python -m slipcover
Traceback (most recent call last):
  File "/Users/pd/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pd/.pyenv/versions/3.10.3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/pd/tmp/venv/lib/python3.10/site-packages/slipcover/__main__.py", line 4, in <module>
    from slipcover import slipcover as sc
  File "/Users/pd/tmp/venv/lib/python3.10/site-packages/slipcover/slipcover.py", line 8, in <module>
    from . import tracker
ImportError: dlopen(/Users/pd/tmp/venv/lib/python3.10/site-packages/slipcover/tracker.cpython-310-darwin.so, 0x0002): tried: '/Users/pd/tmp/venv/lib/python3.10/site-packages/slipcover/tracker.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

Apparently the `slipcover-0.1.4-cp310-cp310-macosx_10_15_universal2.whl` wheel is mislabeled and contains only x86 code.

**Comment by jaltmayerpizzorno** [comment]
@pietrodn, please try from `pip install -i https://test.pypi.org/simple/ slipcover==0.1.4.dev202205051057` and reopen the issue if it didn't resolve it.  Thank you!
