### ISSUE TITLE
ModuleNotFoundError: No module named '_pytest'

### ISSUE THREAD

**Issue by exarkun** [plasma-umass/slipcover#4]
slipcover seems to have an undeclared dependency on pytest now.

```
python -m slipcover run --json --out slipcover.json -m twisted.trial sometestsuite
```

fails:

```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\slipcover\__main__.py", line 153, in <module>
    wrap_pytest()
  File "C:\hostedtoolcache\windows\Python\3.9.12\x64\lib\site-packages\slipcover\__main__.py", line 112, in wrap_pytest
    import _pytest.assertion.rewrite
ModuleNotFoundError: No module named '_pytest'
Error: Process completed with exit code 1.
```

**Comment by jaltmayerpizzorno** [comment]
Ah indeed, I thought about this case but forgot to add it in (it's hard to test, requires a system without pytest).

**Comment by jaltmayerpizzorno** [comment]
Please try again with `pip install -i https://test.pypi.org/simple/ slipcover==0.1.1.dev202204271309` and let me know if that solves it.  Thank you!

**Comment by exarkun** [comment]
Yep, this works for me.  Thanks.
