### ISSUE TITLE
importing subprocess hits AttributeError

### ISSUE THREAD

**Issue by d-b-w** [plasma-umass/slipcover#8]
Using an example test file under Python3.8.10 that only imports subprocess, I see:

    Traceback (most recent call last):
    File "/Users/wandschn/builds/22-2/build/internal/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
    File "/Users/wandschn/builds/22-2/build/internal/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
    File "/Users/wandschn/builds/22-2/build/22-2.VE/lib/python3.8/site-packages/slipcover/__main__.py", line 199, in <module>
        exec(code, script_globals)
    File "/Users/wandschn/builds/22-2/build/mmshare-v5.8/tmp.py", line 1, in <module>
        import subprocess
    File "/Users/wandschn/builds/22-2/build/internal/lib/python3.8/subprocess.py", line 64, in <module>
        import msvcrt
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 914, in _find_spec
    File "/Users/wandschn/builds/22-2/build/22-2.VE/lib/python3.8/site-packages/slipcover/__main__.py", line 40, in find_spec
        found = f.find_spec(fullname, path, target)
    AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'

I'm running on mac, the Python version is 3.8.10. The slipcover version is slipcover==0.1.3.

**Comment by jaltmayerpizzorno** [comment]
Hi, thank you for reporting the issue.  I can’t reproduce it with a simple file importing `subprocess`, on a mac and with Python 3.8, but the backtrace is helpful.

**Comment by jaltmayerpizzorno** [comment]
Could you try again with the build from
```pip install -i https://test.pypi.org/simple/ slipcover==0.1.3.dev202205030931``` ?
Thank you!

**Comment by d-b-w** [comment]
That works for me! nicely done.

Was there any additional version information that would have been useful to you?

**Comment by jaltmayerpizzorno** [comment]
> That works for me! nicely done.

Thank you :) 

> Was there any additional version information that would have been useful to you?

Really just more information on the steps to reproduce, maybe a code excerpt showing the problem, etc.

**Comment by d-b-w** [comment]
fair - we have a custom Python build so generating examples for external use is a bit tricky :/
